version: '3'
services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FRONTEND_URL=http://host.docker.internal:3000
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network

  worker:
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FRONTEND_URL=http://host.docker.internal:3000
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
