version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      platforms:
        - linux/amd64
    ports:
      - "5001:5001"
    env_file:
      - vp.env
    environment:
      - WORKERS=4
      - TIMEOUT=300
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
      platforms:
        - linux/amd64
    volumes:
      - ytdl_cache:/app/ytdl_cache
    env_file:
      - vp.env
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '8'
          memory: 16G
        reservations:
          cpus: '4'
          memory: 8G
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ytdl_cache: 